// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuicmuhoamzcriggrfni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1aWNtdWhvYW16Y3JpZ2dyZm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjA0MjUsImV4cCI6MjA1NDc5NjQyNX0.a1mn_bdquNjTuPM2B8um-Uj88KHE5S-UQGPB0Atgt6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);